# Generated by Django 3.2.13 on 2022-05-17 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0010_auto_20220517_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='spending',
            name='spent_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 15, 9, 34, 283184), verbose_name='Time spent'),
        ),
    ]
