# Generated by Django 3.2.13 on 2022-05-17 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0012_alter_spending_spent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='spent_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 15, 11, 19, 71048), verbose_name='Time spent'),
        ),
    ]
