# Generated by Django 3.2.13 on 2022-05-17 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0015_alter_spending_spent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='spent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time spent'),
        ),
    ]
