# Generated by Django 3.2.13 on 2022-05-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0016_alter_spending_spent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='amount_normalized',
            field=models.IntegerField(default=0),
        ),
    ]
